modLoader="javafml" #mandatory
loaderVersion="[30,)" #mandatory (30 is current forge version)
issueTrackerURL="https://github.com/lazynessmind/Snad/issues" #optional
[[mods]] #mandatory
modId="snad" #mandatory
version="1.8.1.10a" #mandatory
displayName="Snad" #mandatory
updateJSONURL="https://raw.githubusercontent.com/lazynessmind/Snad/master/update.json" #optional
displayURL="https://www.curseforge.com/minecraft/mc-mods/snad-back-to-the-past" #optional
logoFile="" #optional
credits="TheRoBrit (Original mod)" #optional
authors="lazynessmind (me), TheRoBrit" #optional
description='''You're finally able to have your sugarcane grow faster. What could possibly be better than that?''' #mandatory

[[dependencies.examplemod]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[30,)" #mandatory
    ordering="NONE"
    side="BOTH"